version: 2

jobs:
  build:
    docker:
      - image: gengjiawen/node-build
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build v8 docs
          command: |
            npx envinfo
            git clone https://github.com/v8/v8 --depth=1
            doxygen
            7z a v8-docs.7z ./html
            ls -lh
      - store_artifacts:
          path: ./v8-docs.7z

workflows:
  version: 2
  main:
    jobs:
      - build
